name: Tests
on:
  push:
    branches:
      - main
      - dev
jobs:
  functional:
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.io/elasticsearch:8.16.6
        ports:
          - 9200:9200
        env:
          xpack.security.enabled: "false"
          discovery.type: "single-node"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        options: >-
          --health-cmd "curl -s http://localhost:9200 | grep -q 'You Know, for Search'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - name: Install dependencies
        run: go mod tidy
      - name: Run
        run: |
          go test -v --run _Integration ./tests